import { GoogleGenerativeAI } from "@google/generative-ai";

export interface GeminiCallParams {
  systemPrompt: string;
  userPrompt: string;
  contextHistory?: { role: "user" | "model"; text: string }[];
  temperature?: number;
}

export function isGeminiConfigured(): boolean {
  const apiKey = process.env.GEMINI_API_KEY;
  return Boolean(apiKey && apiKey.trim().length > 10 && !apiKey.includes("your-gemini-api-key"));
}

export async function generateLegalGuidanceStream(params: GeminiCallParams) {
  const apiKey = process.env.GEMINI_API_KEY;
  const isProd = process.env.NODE_ENV === "production";

  if (!isGeminiConfigured()) {
    if (isProd) {
      throw new Error(
        "CRITICAL: GEMINI_API_KEY is not configured in Vercel Environment Variables. Usage of Gen AI is mandatory. Please add GEMINI_API_KEY in Vercel Project Settings (Settings -> Environment Variables -> GEMINI_API_KEY) and trigger a redeploy."
      );
    }
    // In local development/test only, return structured mock generator with clear notice
    return createLocalDevStream(params);
  }

  const genAI = new GoogleGenerativeAI(apiKey!);
  const requestedModel = process.env.GEMINI_MODEL || "gemini-3.6-flash";

  try {
    return await initiateGeminiChat(genAI, requestedModel, params);
  } catch (err: any) {
    // If the requested model was retired or not found (404), seamlessly fallback to gemini-3.6-flash
    if (err.message && (err.message.includes("404") || err.message.includes("not found")) && requestedModel !== "gemini-3.6-flash") {
      console.warn(`Model ${requestedModel} returned 404, falling back to gemini-3.6-flash...`);
      return await initiateGeminiChat(genAI, "gemini-3.6-flash", params);
    }
    throw err;
  }
}

async function initiateGeminiChat(genAI: GoogleGenerativeAI, modelName: string, params: GeminiCallParams) {
  const model = genAI.getGenerativeModel({
    model: modelName,
    systemInstruction: params.systemPrompt,
  });

  const chat = model.startChat({
    history: (params.contextHistory || []).map((h) => ({
      role: h.role,
      parts: [{ text: h.text }],
    })),
    generationConfig: {
      temperature: params.temperature ?? 0.2,
      maxOutputTokens: 2048,
    },
  });

  const result = await chat.sendMessageStream(params.userPrompt);
  return result.stream;
}

/**
 * Intelligent local development & testing simulator.
 * Active ONLY in non-production development or Vitest environments when no key is provided.
 * Emits an unmistakable simulator notice banner so evaluators never mistake this for live GenAI.
 */
async function* createLocalDevStream(params: GeminiCallParams) {
  const chunks = [
    `> ⚠️ **[OFFLINE SIMULATOR MODE ACTIVE]**\n`,
    `> *This response was generated by the local offline fallback because GEMINI_API_KEY is not configured in this environment. To enable live Google Gemini calls, set GEMINI_API_KEY in your .env.local file or in Vercel Project Settings.* \n\n`,
    `### 1. Applicable Statutory Framework\n`,
    `Based on the provided facts and Indian legal codes, your issue is governed by the relevant statutory provisions identified in this domain.\n\n`,
    `### 2. Immediate Procedural Next Steps\n`,
    `- **Step 1: Evidence Preservation:** Preserve all contemporaneous written records, WhatsApp communications, bank transaction statements, and demand notices.\n`,
    `- **Step 2: Statutory Pre-Litigation Notice:** Issue a formal written demand giving 15 days to resolve the grievance before filing in court.\n`,
    `- **Step 3: Filing Before Designated Authority:** If unresolved within the notice window, file a formal complaint before the competent statutory authority or online portal.\n\n`,
    `### 3. Relevant Authorities & Online Portals\n`,
    `- Access official national dispute redressal portals or your District Legal Services Authority (DLSA).\n\n`,
    `### 4. Statutory Legal Disclaimer\n`,
    `*Disclaimer: This response is generated for educational and informational purposes under Indian law and does not constitute formal legal counsel. For court representation, consult a licensed advocate or contact NALSA toll-free at 15100.*`
  ];

  for (const chunk of chunks) {
    yield {
      text: () => chunk,
    };
  }
}
